apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservice
  namespace: default
spec:
  tls:
    - hosts:
        - <hostname> # need to edit
      secretName: <secret name> # need to edit
  rules:
    - host: <hostname> # need to edit
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
